// <auto-generated />
using System;
using LearningProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LearningProject.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20190219121240_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LearningProject.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ShortDescription");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            ImageUrl = "images.jpg",
                            ShortDescription = "Designing premium interiors is a rejection of typical planning, finishing and decoration decisions in favor of a unique environment that best meets the needs of the customer.",
                            Title = "Luxury interior in the design of apartments and houses"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "images.jpg",
                            ShortDescription = "Designing premium interiors is a rejection of typical planning, finishing and decoration decisions in favor of a unique environment that best meets the needs of the customer.",
                            Title = "Luxury interior in the design of apartments and houses"
                        });
                });

            modelBuilder.Entity("LearningProject.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("LearningProject.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<int?>("RoleId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Password = "admin1",
                            RoleId = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 3,
                            Password = "volodya1",
                            RoleId = 2,
                            UserName = "volodya"
                        });
                });

            modelBuilder.Entity("LearningProject.Data.Models.User", b =>
                {
                    b.HasOne("LearningProject.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
